import AdminHeader from "./Header"
import BrandModal from "./Brands/BrandModal"
import UpdateBrand from "./Brands/UpdateBrand"
import BrandById from "./Brands/BrandById"
import CategoryById from "./Categories/CategoryById"
import CategoryModal from "./Categories/CategoryModal"
import Updatecategory from "./Categories/UpdateCategory"
import ProductModal from "./Products/ProductModal"
import UpdateProduct from "./Products/UpdateProduct"
import ProductByName from "./Products/ProductByID"
import ImageModal from "./ImageModal"
import OrderByID from "./orders/OrderByID"
import UpdateOrder from "./orders/UpdateOrder"
import UserModal from "./Users/UserModal"
import UpdateUser from "./Users/UpdateUser"
import UserByEmail from "./Users/UserByEmail"

export { AdminHeader, BrandModal, UpdateBrand, BrandById, CategoryById, CategoryModal, Updatecategory, ProductModal, UpdateProduct, ProductByName, ImageModal, OrderByID, UpdateOrder, UserModal, UpdateUser, UserByEmail }